users_name_max_length: 50
users_email_max_length: 255
users_password_min_length: 6
users:
  role:
    admin: 0
    moderator: 1
    critic: 2
    normal: 3

movies:
  name_max_length: 100
  info_max_length: 1000
  index_poster_height: 200
  index_poster_width: 200
  paginate: 10
  poster_accept: "image/jpeg,image/gif,image/png"

tvshows:
  name_max_length: 100
  info_max_length: 1000
  index_poster_height: 200
  index_poster_width: 200
  paginate: 10
  poster_accept: "image/jpeg,image/gif,image/png"
